apiVersion: v1
kind: Service
metadata:
 name: myweb-service
 labels:
  app: myweb
  version: v1
spec:
 type: LoadBalancer
 selector:
   app: myweb
   version: v1
 ports:
 - protocol: TCP
   port: 80
   targetPort: 80
